###############################################################################
# Makefile for the project AVR-MIDI
###############################################################################

TARGET = ALL

all : mico/mico.hex

mico/mico.hex: main.c
	cd mico ; make

clean:
	( cd mico ; make clean)	
